### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by kubilay-kara** [hiukim/mind-ar-js#310]
mindar-image-three.prod.js:2 Uncaught (in promise) RangeError: Extra 5229 byte(s) found at buffer[1]
    at t.createNoExtraBytesError (mindar-image-three.prod.js:2:16500)
    at t.decodeSingleSync (mindar-image-three.prod.js:2:16675)
    at Module.V (mindar-image-three.prod.js:2:24874)
    at Compiler.importData (mindar-image-three.prod.js:2:1757846)
    at Controller.addImageTargetsFromBuffer (mindar-image-three.prod.js:2:1759605)
    at mindar-image-three.prod.js:2:1759527

**Comment by kubilay-kara** [comment]
when i use same code it worked on a plain html, it cause problem on my php page, its not related to mindar
