### ISSUE TITLE
image target compiler not working

### ISSUE THREAD

**Issue by zerocool-z1** [hiukim/mind-ar-js#382]
I tried uploading an image in the copiler but from last 15 min. progress is stuck on 0%, image is only 87 kb. when i opend the console it showed me errors mentioned below

mindar-image.prod.js:2 Could not get context for WebGL version 2

mindar-image.prod.js:2 Could not get context for WebGL version 1

mindar-image.prod.js:2 Initialization of backend webgl failed
ns @ mindar-image.prod.js:2
mindar-image.prod.js:2 Error: WebGL is not supported on this device
    at new hD (mindar-image.prod.js:2:805553)
    at Object.factory (mindar-image.prod.js:2:826632)
    at ha.initializeBackend (mindar-image.prod.js:2:75497)
    at ha.initializeBackendsAndReturnBest (mindar-image.prod.js:2:76855)
    at get backend [as backend] (mindar-image.prod.js:2:73970)
    at ha.makeTensor (mindar-image.prod.js:2:81223)
    at Ea (mindar-image.prod.js:2:96401)
    at Module.$a (mindar-image.prod.js:2:96445)
    at mindar-image.prod.js:2:1143375
    at mindar-image.prod.js:2:77733
ns @ mindar-image.prod.js:2

mindar-image.prod.js:2 Uncaught (in promise) TypeError: r.backend(...).compileAndRun is not a function
    at Detector._compileAndRun (mindar-image.prod.js:2:1172690)
    at mindar-image.prod.js:2:1170747
    at mindar-image.prod.js:2:77733
    at ha.scopedRun (mindar-image.prod.js:2:77854)
    at ha.tidy (mindar-image.prod.js:2:77667)
    at Module.Xo (mindar-image.prod.js:2:142674)
    at Detector._applyFilter (mindar-image.prod.js:2:1170685)
    at Detector.detect (mindar-image.prod.js:2:1153273)
    at mindar-image.prod.js:2:1143464
    at mindar-image.prod.js:2:77733

**Comment by dvbridges** [comment]
Hi, the error "Error: WebGL is not supported on this device" suggests your device does not support webgl.

**Comment by hiukim** [comment]
`WebGL is not supported on this device`.  Try a different browser/device maybe
