### ISSUE TITLE
import { MindARThree } from 'mind-ar/dist/mindar-face-three.prod.js';

### ISSUE THREAD

**Issue by alfa95** [hiukim/mind-ar-js#387]
While using the face library getting a error

core.mjs:8416 ERROR Error: Uncaught (in promise): TypeError: pB.FaceMesh is not a constructor
TypeError: pB.FaceMesh is not a constructor
    at new uB (controller-212bb69c.js:4311:48)
    at controller-212bb69c.js:8212:39
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Object.onInvoke (core.mjs:24205:33)
    at _ZoneDelegate.invoke (zone.js:374:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1278:36
    at resolvePromise (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:25:1)
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Object.onInvoke (core.mjs:24205:33)
    at _ZoneDelegate.invoke (zone.js:374:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1278:36
handleError @ core.mjs:8416
next @ core.mjs:24886
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:20895
(anonymous) @ core.mjs:24231
invoke @ zone.js:375
run @ zone.js:134
runOutsideAngular @ core.mjs:24104
onHandleError @ core.mjs:24231
handleError @ zone.js:379
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1075
drainMicroTaskQueue @ zone.js:595
invokeTask @ zone.js:494
invokeTask @ zone.js:1664
globalCallback @ zone.js:1695
globalZoneAwareCallback @ zone.js:1728
Show 22 more frames

**Comment by hiukim** [comment]
I'm investigating the issue. maybe use v1.2.0 first

**Comment by hiukim** [comment]
should be fixed in v1.2.2. thx
