### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by redragonx** [hiukim/mind-ar-js#444]
Hi,

I'm using V1.2.3 of mind ar and getting this error:

```


- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 249 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 114 ms (20 modules)
- wait compiling /page (client and server)...
- event compiled client and server successfully in 2.9s (2380 modules)
- error node_modules/mind-ar/dist/mindar-image-three.prod.js (13345:0) @ eval
- error ReferenceError: window is not defined
    at __webpack_require__ (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/webpack-runtime.js:33:42)
    at eval (./app/Components/PageComponents/TestExperienceComp/SubComps/ThreeJSModule.js:6:97)
    at (ssr)/./app/Components/PageComponents/TestExperienceComp/SubComps/ThreeJSModule.js (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/app/page.js:10104:1)
    at __webpack_require__ (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/webpack-runtime.js:33:42)
    at eval (./app/Components/PageComponents/TestExperienceComp/SubComps/ARJSModule.tsx:8:72)
    at (ssr)/./app/Components/PageComponents/TestExperienceComp/SubComps/ARJSModule.tsx (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/app/page.js:10093:1)
    at __webpack_require__ (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/webpack-runtime.js:33:42)
    at eval (./app/Components/PageComponents/TestExperienceComp/TestExperienceComp.tsx:14:78)
    at (ssr)/./app/Components/PageComponents/TestExperienceComp/TestExperienceComp.tsx (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/app/page.js:10115:1)
    at __webpack_require__ (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx:15:122)
    at (ssr)/./app/page.tsx (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/app/page.js:10236:1)
    at __webpack_require__ (/home/stephen/disks/src-main/src/xrgoods/xr-card-studio/.next/server/webpack-runtime.js:33:42)
null
- wait compiling /favicon.ico/route (client and server)...
- event compiled successfully in 251 ms (1238 modules)

```

**Comment by BostonLeeK** [comment]
You have this problem cos you using next.js 13 (how I understand) that by default have ssr enable. It try to call window on server that server doesn't have. You must set to execute this part of code on client using "use client" or useEffect and load library dynamic.

**Comment by redragonx** [comment]
yes, thanks! I'll try that.
